apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      hostNetwork: true
      containers:
        - name: petclinic-container
          image: mk283/spring-petclinic:2
          ports:
            - containerPort: 8081
          command: ["java"]
          args: ["-jar", "/app.jar", "--server.port=8081"]

