apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: NodePort
  selector:
    app: petclinic
    color: blue  # default target; change to "green" when switching
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30036  # optional; Kubernetes can auto-assign if omitted

