apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30036  # Optional: can be omitted to auto-assign a port

